### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by theGolyo** [large64/The-Game#1]
Hi Dénes!
It was nice meeting you on Monday! I'd like to request a few addtional tweaks from you if you have the time :)
1. Deploy the bundle somewhere so even non-techie people can take a look (github pages is enough)
2. Add a simple pause/resume functionality on keypress (i.e: "p")
3. The `Main` class handles a lot of different stuff, and you already have classes that could help out with some of its responsibilites, can you refactor/break it up a bit? :) I'm curious about your approach on this one! 

Feel free to take your time if needed!
Marton

**Comment by large64** [comment]
Hi!
Thank you for your time and comment, I think I've fulfilled all your wishes. Please check it if you have some time!
The game is now available at https://large64.github.io/The-Game/
See you

**Comment by theGolyo** [comment]
Thanks for the time&work Denes!
Marton
